# 🔗 Links:
# Source file: https://github.com/obytes/react-native-template-obytes/blob/master/.github/workflows/type-check.yml

name: Lint TS

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  type-check:
    name: Type Check (tsc)
    runs-on: ubuntu-latest
    steps:
      - name: 📦 Checkout project repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}/.github/actions        

      - name: 📦 Setup Node + PNPM + install deps
        uses: ./.github/aactions/setup-node-pnpm-install/action.yml

      - name: Check types with tsc
        id: tsc_check
        run: yarn tsc

      - name: Check lint
        id: lint_check
        run: yarn lint
