name: Lint Code Base

on: [push, pull_request]

jobs:
  run-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      - name: Install Dependencies
        run: yarn --prefer-offline --ignore-engines

      - name: Check lint
        id: lint_check
        run: yarn lint          

      - name: Unit test
        id: unit_test
        run: yarn test

